CREATE TABLE IF NOT EXISTS store_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shop TEXT NOT NULL UNIQUE,
  vendor TEXT NOT NULL DEFAULT '',
  language TEXT NOT NULL DEFAULT 'English',
  region TEXT NOT NULL DEFAULT '',
  default_inventory INTEGER NOT NULL DEFAULT 99,
  track_inventory INTEGER NOT NULL DEFAULT 1,
  retail_price_multiplier REAL NOT NULL DEFAULT 1.0,
  compare_at_price_multiplier REAL NOT NULL DEFAULT 0,
  retail_price_manual INTEGER NOT NULL DEFAULT 0,
  compare_at_price_manual INTEGER NOT NULL DEFAULT 0,
  price_rounding TEXT NOT NULL DEFAULT '.95',
  product_status TEXT NOT NULL DEFAULT 'ACTIVE',
  sales_channels INTEGER NOT NULL DEFAULT 1,
  vat_enabled INTEGER NOT NULL DEFAULT 1,
  alt_text_optimization INTEGER NOT NULL DEFAULT 1,
  variant_pricing INTEGER NOT NULL DEFAULT 0,
  inventory_policy TEXT NOT NULL DEFAULT 'CONTINUE',
  product_tags_enabled INTEGER NOT NULL DEFAULT 0,
  product_type_enabled INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);
